---
- name: Install Ollama
  become: true
  ansible.builtin.shell:
    cmd: curl -fsSL https://ollama.com/install.sh | sh
    creates: /usr/local/bin/ollama

- name: Install Ollama Systemd Unit File
  become: true
  ansible.builtin.template:
    src: ollama.service.j2
    dest: /etc/systemd/system/ollama.service
  notify: Restart Ollama

- name: Ensure Ollama Daemon is Running
  become: true
  ansible.builtin.systemd:
    name: ollama
    daemon_reload: true
    enabled: true
    state: started
