---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
    state: present
    update_cache: true

- name: Check for nvidia-smi
  ansible.builtin.stat:
    path: /usr/bin/nvidia-smi
  register: nvidia_smi

- name: Install Nvidia Drivers
  become: true
  when: not nvidia_smi.stat.exists
  block:
    - name: Install Nvidia Drivers | Server Drivers
      ansible.builtin.command: ubuntu-drivers install --gpgpu
    - name: Install Nvidia Drivers | Common Drivers
      ansible.builtin.command: ubuntu-drivers install

- name: Install Ollama
  become: true
  ansible.builtin.shell:
    cmd: curl -fsSL https://ollama.com/install.sh | sh
    creates: /usr/local/bin/ollama

- name: Ensure Ollama Daemon is Running
  become: true
  ansible.builtin.systemd:
    name: ollama
    daemon_reload: true
    enabled: true
    state: started

- name: Ensure OpenWebUI Directory Exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/open_webui
    state: "directory"
    mode: "0755"

- name: Install Docker Compose File
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/open_webui/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Stop Docker Compose Service
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/open_webui
    pull: always
    state: stopped
    remove_orphans: true

- name: Start Docker Compose Service
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/open_webui
    pull: always
    state: present
    remove_orphans: true
