- name: Restart Reth
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: reth
    enabled: true
    state: restarted

- name: Restart Lighthouse
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: lighthouse
    enabled: true
    state: restarted
