---
- name: Nginx Base Role | Install Nginx
  when: not nginx_base_apt_repo_enabled
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - nginx

- name: Nginx Base Role | Install N
  when: nginx_base_apt_repo_enabled
  become: true
  block:
    - name: Nginx Base Role | Install Nginx from Nginx Repos
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - ubuntu-keyring

    - name: Nginx Base Role | Install NGINX and Certbot | Download NGINX Signing Key
      ansible.builtin.shell: |
        curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: Nginx Base Role | Install NGINX and Certbot | Add NGINX Apt Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
        state: present
        update_cache: true
        filename: nginx

    - name: Nginx Base Role | Install NGINX and Certbot | Install Apt Packages
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - nginx
          - python3-certbot-nginx

- name: Nginx Base Role | Ensure NGINX service is running and enabled
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Nginx Base Role | Create Nginx Directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Nginx Base Role | Remove Default NGINX Config
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  notify: Restart Nginx

- name: Nginx Base Role | Configure Nginx
  become: true
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Nginx Base Role | Test NGINX configuration
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false
