{{- $name := include "cloudflare_tunnel.name" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-cert-secret
type: Opaque
stringData:
  credentials.json: |
    {
        "AccountTag"   : "{{ .Values.accounttag }}",
        "TunnelID"     : "{{ .Values.tunnelid }}",
        "TunnelName"   : "{{ .Values.tunnelname }}",
        "TunnelSecret" : "{{ .Values.tunnelsecret }}"
    }
