
persistence:
  size: 5Gi
  existingClaim: "hostpath-pvc-00"

service:
  type: ClusterIP

ingress:
  enabled: true
  pathType: Prefix
  hostname: moodle.gooseops.com
  tls: false
  ## @param ingress.extraHosts The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## extraHosts:
  ## - name: minio.local
  ##   path: /
  ##
  
  ## @param ingress.secrets If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ## e.g:
  ## - name: minio.local-tls
  ##   key:
  ##   certificate:
  ##
  secrets: []
  ingressClassName: "traefik"
 
mariadb:
  primary:
    persistence:
      enabled: true
      size: 5Gi
      existingClaim: "hostpath-pvc-01"
