---
pihole_data_dir: "/var/lib/pihole"
pihole_image_version: "2025.08.0"
pihole_tz: "America/New_York"
pihole_init_pw: "foobar123"
pihole_docker_compose_dir: "/home/{{ ansible_user }}/pihole"
pihole_system_primary_dns: "1.1.1.3"
pihole_system_fallback_dns: "1.0.0.3"
