
- name: Install Packages
  become: true
  ansible.builtin.apt:
    pkg:
      - wireguard
    state: present

- name: Ensure Wireguard Service is Stopped
  become: true
  ansible.builtin.systemd:
    name: wg-quick@wg0
    daemon_reload: true
    enabled: true
    state: stopped

- name: Ensure WireGuard directory exists
  become: true
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate wg0.conf configuration file
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'

- name: Ensure Wireguard Service is Started
  become: true
  ansible.builtin.systemd:
    name: wg-quick@wg0
    daemon_reload: true
    enabled: true
    state: started

- name: Enable IPv4 Forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
