---
- name: Ensure required dependencies are installed
  become: true
  ansible.builtin.apt:
    name:
      - curl
    state: present
    update_cache: yes
  tags:
    - cloudflare-tunnel
    - apt-packages

- name: Install cloudflared
  become: true
  block:
    - name: Install cloudflared | Create keyrings directory
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
    - name: Install cloudflared | Download cloudflared gpg key
      ansible.builtin.shell:
        cmd: curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
        creates: /usr/share/keyrings/cloudflare-main.gpg
    - name: Install cloudflared | Add cloudflared to apt list
      ansible.builtin.template:
        src: cloudflared.list.j2
        dest: /etc/apt/sources.list.d/cloudflared.list
    - name: Install cloudflared | Install cloudflared apt package
      ansible.builtin.apt:
        name:
          - cloudflared
        state: present
        update_cache: yes

- name: Configure cloudflared tunnel
  become: true
  block:
    - name: Configure cloudflared tunnel | Create cloudflared configuration directory
      ansible.builtin.file:
        path: /etc/cloudflared
        state: directory
        mode: '0755'
    - name: Configure cloudflared tunnel | Add config.yaml file
      ansible.builtin.template:
        src: config.yml.j2
        dest: /etc/cloudflared/config.yml
    - name: Configure cloudflared tunnel | Add credentials.json file
      ansible.builtin.template:
        src: credentials.json.j2
        dest: /etc/cloudflared/credentials.json

- name: Create cloudflared service
  become: true
  block:
    - name: Create cloudflared service | Install service file
      ansible.builtin.command:
        cmd: cloudflared service install
        creates: /etc/systemd/system/cloudflared.service
    - name: Create cloudflared service | Enable and run cloudflared.service
      ansible.builtin.systemd:
        name: cloudflared
        enabled: yes
        state: started
