---
- name: Install NGINX and Certbot
  become: true
  ansible.builtin.apt:
    name: 
      - nginx
    state: present
    update-cache: true
  
- name: Ensure NGINX service is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Configure nginx
  become: true
  block:
    - name: Configure nginx | Remove default nginx config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Configure nginx | Install tls directory
      ansible.builtin.file:
        path: /etc/nginx/tls
        state: directory
        mode: '0600'

    - name: Configure nginx | Install cert
      ansible.builtin.copy:
        content: "{{ cert_pem }}"
        dest: "/etc/nginx/tls/{{ domain }}.crt"
        owner: root
        group: root
        mode: '0644'

    - name: Configure nginx | Install prvkey
      copy:
        content: "{{ prvkey_pem }}"
        dest: /etc/nginx/tls/{{ domain }}.key
        owner: root
        group: root
        mode: '0600'

    - name: Configure nginx | Install {{ domain }} config
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ domain }}

    - name: Configure nginx | Enable {{ domain }} config
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link

    - name: Configure nginx | Secure nginx version
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: '# server_tokens off;'
        line: '        server_tokens off;'

- name: Test NGINX configuration
  become: true
  ansible.builtin.command: nginx -t

- name: Reload NGINX to apply SSL certificates
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
