---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-00
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/hoststorage-00
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-00
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-01
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/hoststorage-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-02
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/hoststorage-02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
