---
- name: ubuntu-docker | Apt packages
  become: true
  ansible.builtin.apt:
    name:
      - openssl
      - curl
      - ca-certificates
    state: present
    update-cache: true
  tags:
    - docker
    - apt-packages

- name: ubuntu-docker | Install docker
  become: true
  block:
    - name: ubuntu-docker | install docker | create keyrings directory
      ansible.builtin.file:
        mode: "0755"
        path: /etc/apt/keyrings
        state: "directory"

    - name: ubuntu-docker | install docker | download docker gpg key
      ansible.builtin.get_url:
        dest: /etc/apt/keyrings/docker.asc
        url: https://download.docker.com/linux/ubuntu/gpg
        mode: "0644"

    - name: ubuntu-docker | install docker | add apt repository
      ansible.builtin.shell: |
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: ubuntu-docker | install docker | install docker apt packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update-cache: true
      tags:
        - docker
        - apt-packages

- name: ubuntu-docker | Configure Docker Daemon
  become: true
  ansible.builtin.copy:
    content: "{{ docker_config_daemon_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart Docker

- name: ubuntu-docker | Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: ubuntu-docker | Reset connection for new group
  ansible.builtin.meta: reset_connection
