---
- hosts: all
  roles:
    - role: holesky
      vars:
        holesky_jwt_secret:  "{{ lookup('ansible.builtin.env', 'HOLESKY_JWT_SECRET') }}"
        checkpoint_sync_url: "{{ lookup('ansible.builtin.env', 'HOLESKY_CHECKPOINT_SYNC_URL') }}"

    - role: swap
      vars:
        swapfile_size: 16G
