---
- name: Nginx Proxy | Write Configs From Loop | Obtain SSL certificates using Certbot
  when:
    - item.nginx_proxy_tls_enabled is defined and item.nginx_proxy_tls_enabled
    - item.nginx_proxy_crt_type is defined and item.nginx_proxy_crt_type == "letsencrypt"
  become: true
  ansible.builtin.command: certbot certonly --nginx -d {{ item.nginx_proxy_domain }} --non-interactive --agree-tos --email {{ item.nginx_proxy_email }}
  notify: Restart Nginx

- name: Nginx Proxy | Write Configs From Loop | Private Cert
  when: item.nginx_proxy_crt_type is defined and item.nginx_proxy_crt_type == "private"
  become: true
  rescue:
    - name: Nginx Proxy | Write Configs From Loop | Private Cert | Fail if BYO cert is missing
      ansible.builtin.fail:
        msg: "BYO certificate or key is missing. Set `nginx_proxy_tls_crt` and `nginx_proxy_tls_key` role variables."
  block:
    - name: Nginx Proxy | Write Configs From Loop | Private Cert | Write TLS Certificate
      ansible.builtin.copy:
        content: "{{ item.nginx_proxy_tls_crt }}"
        dest: /etc/nginx/tls/certs/{{ item.nginx_proxy_domain }}.crt
        mode: '0600'
        owner: www-data
        group: www-data

    - name: Nginx Proxy | Write Configs From Loop | Private Cert | Write TLS Private Key
      ansible.builtin.copy:
        content: "{{ item.nginx_proxy_tls_key }}"
        dest: /etc/nginx/tls/private/{{ item.nginx_proxy_domain }}.key
        mode: '0600'
        owner: www-data
        group: www-data

- name: Nginx Proxy | Write Configs From Loop | HTTP Servers
  when: item.nginx_proxy_http_server is defined
  become: true
  block:
    - name: Nginx Proxy | Write Configs From Loop | HTTP Servers | Write Config
      ansible.builtin.copy:
        content: "{{ item.nginx_proxy_http_server }}"
        dest: /etc/nginx/sites-available/{{ item.nginx_proxy_domain }}
        mode: "0644"
      notify: Restart Nginx

    - name: Nginx Proxy | Write Configs From Loop | HTTP Servers | Enable Config
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ item.nginx_proxy_domain }}
        dest: /etc/nginx/sites-enabled/{{ item.nginx_proxy_domain }}
        state: link
      notify: Restart Nginx

- name: Nginx Proxy | Write Configs From Loop | Stream Servers
  when: item.nginx_proxy_stream_server is defined
  become: true
  ansible.builtin.copy:
    content: "{{ item.nginx_proxy_stream_server }}"
    dest: /etc/nginx/conf.d/stream/{{ item.nginx_proxy_config_name }}.conf
    mode: "0644"
  notify: Restart Nginx

- name: Nginx Proxy | Write Configs From Loop | Test NGINX Config
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false
