---
- name: Nginx Proxy | Full Package
  when: nginx_proxy_stream_enabled
  become: true
  block:
    - name: Nginx Proxy | Full Package | Stream Directory
      ansible.builtin.file:
        path: /etc/nginx/conf.d/stream
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Nginx Proxy | Full Package | Package
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - nginx-full
      notify: Restart Nginx

    - name: Nginx Proxy | Full Package | Config
      ansible.builtin.copy:
        src: stream.conf
        dest: /etc/nginx/conf.d/stream.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Nginx

- name: Nginx Proxy | Ensure Private TLS Directories Exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data
  loop:
    - /etc/nginx/tls/certs
    - /etc/nginx/tls/private

- name: Nginx Proxy | Write Configs From Loop
  include_tasks: ubuntu-nginx-proxy-configs.yml
  loop: "{{ nginx_proxy_configs }}"
  loop_control:
    loop_var: item
  no_log: true
