---
- name: Obtain SSL certificates using Certbot
  ansible.builtin.command: certbot certonly --nginx -d {{ domain }} --non-interactive --agree-tos --email {{ email }}
  become: true
  when: ssl_enabled
  notify: Restart Nginx

- name: Configure NGINX as a reverse proxy
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}
  become: true

- name: Enable NGINX site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link
  become: true

- name: Implement Rate Limit
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "^        server_tokens off;"
    line: "        limit_req_zone $binary_remote_addr zone=one:10m rate=3r/s;"
  notify: Restart Nginx

- name: Remove default NGINX configuration if present
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  notify: Restart Nginx

- name: Test NGINX configuration
  become: true
  ansible.builtin.command: nginx -t
