print("""Once upon a time, in a deep and dark forest, there lived two ogres named Gromm and Kragg. Gromm was a huge, hulking brute with bulging muscles and a fierce scowl on his face. Kragg, on the other hand, was a bit smaller and leaner, but he was just as ferocious as Gromm when it came to defending his family.
Gromm and Kragg were neighbors, and they had known each other since they were young. They both had large families of ogres, with plenty of little ones running around and causing chaos. Gromm had three sons and two daughters, while Kragg had two sons and three daughters.
Despite their rough and tough exteriors, Gromm and Kragg were both very devoted to their families. They spent long hours hunting for food, making sure their homes were secure, and teaching their children how to be strong and fierce like them.
One day, however, a group of humans stumbled upon the ogres' forest. They were a group of adventurers, seeking treasure and adventure in the wilderness. When they saw the ogres and their families, they immediately drew their weapons and prepared to attack.
Gromm and Kragg knew they had to defend their families at all costs. They charged at the humans, roaring and swinging their massive clubs. The battle was intense and brutal, but eventually, the ogres emerged victorious.
After the battle, Gromm and Kragg sat down together to rest and talk. They realized that, despite their differences, they both shared a deep love for their families and would do anything to protect them. From that day on, they became close friends and allies, working together to keep their families safe from any threats that might come their way.
And so, the two ogres and their families lived happily ever after, in their deep and dark forest, far away from the prying eyes of humans and other dangers.
""")

print(""" 
Once upon a time, there was a small cat named Whiskers. Whiskers was a beautiful cat with a soft, gray coat and bright green eyes. However, she had fallen on hard times, and was now starving and weak.
Whiskers wandered through the streets, desperately searching for food. But no matter where she looked, she couldn't find anything to eat. She was so weak that she could barely walk, and she was beginning to lose hope.
One day, as Whiskers was searching for food in an alley, she stumbled upon a group of young children. The children were playing with a ball, and they seemed to be having a great time. Whiskers watched from a distance, too weak to even meow for help.
But one of the children noticed Whiskers, and ran over to her. The child saw how weak and hungry she was, and immediately took action. The child went to get some milk and a small dish, and fed Whiskers. Whiskers was so grateful for the food that she licked the dish clean.
From that day on, the children took care of Whiskers. They gave her food and water, and even made a cozy little bed for her in the alley. Whiskers grew stronger and healthier every day, and she loved spending time with the children.
One day, a terrible storm hit the city. The wind was howling, and the rain was pouring down in sheets. Whiskers was frightened, and didn't know what to do. But the children came to her rescue once again. They huddled together with Whiskers in their arms, and kept her safe and warm throughout the night.
Thanks to the kindness of the children, Whiskers survived her ordeal. She grew strong and healthy, and became a beloved member of the community. The story of the heroic little cat who survived against all odds became famous throughout the city, and the children who saved her became heroes in their own right.
""")

print("""
In the early 1900s, the idea of human flight was still a dream that many people had, but few believed could be realized. However, two brothers from Dayton, Ohio, named Wilbur and Orville Wright, were determined to make this dream a reality.
The Wright brothers had been interested in flight for years and had studied the movements of birds and other flying creatures to try and understand the principles of flight. They conducted numerous experiments with gliders and kites, but they knew that in order to achieve true flight, they needed to build a powered aircraft.
In 1903, the Wright brothers built their first powered aircraft, which they called the Wright Flyer. It was a biplane with a wingspan of 40 feet and a weight of just over 600 pounds. The Flyer was powered by a gasoline engine that produced 12 horsepower and was connected to two wooden propellers.
On December 17, 1903, at Kitty Hawk, North Carolina, the Wright brothers made history by achieving the first powered flight. The flight lasted just 12 seconds and covered a distance of only 120 feet, but it was a significant achievement in the history of aviation.
Over the next few years, the Wright brothers continued to refine their design and improve their aircraft. They made longer flights and were able to fly higher and farther. In 1908, they flew the Wright Flyer for over an hour, covering a distance of more than 40 miles.
The Wright brothers' invention of the airplane revolutionized the way people traveled and changed the course of history. It opened up new possibilities for transportation, commerce, and even warfare. Today, air travel is a common and essential mode of transportation, and it all started with the determination and ingenuity of two brothers from Ohio.
""")